<?php
/**
 * WalkthroughView Template
 *
 * @var $this Qubes\Support\Applications\Front\Walkthrough\Views\WalkthroughView
 */
$walkthrough = $this->getWalkthrough();
$step = $this->getCurrentStep();
?>
<h1><?= $walkthrough->title; ?></h1>
<h2><?= $walkthrough->subTitle; ?></h2>
<div id="walkthrough-description">
  <?= $this->getHtmlFromMarkdown($walkthrough->description) ?>
</div>
<div class="step <?= sprintf('step-%d', $step->id()) ?>">
  <h3><?= $step->title ?></h3>
  <?= $this->getHtmlFromMarkdown($step->content) ?>
</div>

<?php if($this->getPreviousStepUrl()) : ?>
  <a href="<?= $this->getPreviousStepUrl() ?>">
    Previous Step
  </a>
<?php endif; ?>

<?php if($this->getNextStepUrl()) : ?>
  <a href="<?= $this->getNextStepUrl() ?>">
    Next Step
  </a>
<?php endif; ?>
