<?php
/**
 * Author: oke.ugwu
 * Date: 31/07/13 10:15
 *
 * @var $this \Qubes\Support\Applications\Back\Category\Views\Index
 */
?>
<h1>Categories</h1>
<a href="<?= $this->baseUri() . '/new'; ?>"
   class="btn btn-success pull-right"
   style="margin-top:-20px;">
  <i class="icon-plus icon-white"></i>
  Add Category</a>
<div class="clearfix"></div>
<div style="margin-top:10px;"></div>
<?php if(Session::getFlash('msg')): ?>
  <div class="alert alert-<?= Session::getFlash('msg')->type; ?>">
    <?= Session::getFlash('msg')->text; ?>
  </div>
<?php endif; ?>
<table class="table table-striped table-bordered table-hover">
  <tr class="info">
    <th>Title</th>
    <th>Sub Title</th>
    <th>Description</th>
    <th>Parent</th>
    <th></th>
  </tr>
  <?php foreach($this->getCategories() as $category): ?>
    <tr>
      <td>
        <a href="<?= $this->baseUri() . '/' . $category->id() . '/edit/'; ?>">
          <?= $category->title; ?>
        </a>
      </td>
      <td><?= $category->subTitle; ?></td>
      <td><?= $category->description; ?></td>
      <td>
        <?=
        ($category->getParentCategory()) ?
          $category->getParentCategory()->title : '--'; ?>
      </td>
      <td>
        <a href="<?= $this->baseUri() . '/' . $category->id() . '/edit/'; ?>"
           title="Edit"><i class="icon-edit"></i></a>
        <a href="<?= $this->baseUri() . '/' . $category->id() . '/delete/'; ?>"
           title="Delete"><i class="icon-trash"></i></a>
      </td>
    </tr>
  <?php endforeach; ?>
</table>

