<?php
/**
 * Author: oke.ugwu
 * Date: 31/07/13 10:15
 *
 * @var $this \Qubes\Support\Applications\Back\User\Views\Index
 */
?>
<h1>Users</h1>
<a href="/<?= $this->baseUri() . '/new'; ?>"
   class="btn btn-success pull-right"
   style="margin-top:-20px;">
  <i class="icon-plus icon-white"></i>
  Add User</a>
<div class="clearfix"></div>
<div style="margin-top:10px;"></div>
<?php if(Session::getFlash('msg')): ?>
  <div class="alert alert-<?= Session::getFlash('msg')->type; ?>">
    <?= Session::getFlash('msg')->message; ?>
  </div>
<?php endif; ?>
<table class="table table-striped table-bordered table-hover">
  <tr class="info">
    <th>Username</th>
    <th>Email</th>
    <th>Display Name</th>
    <th></th>
  </tr>
  <?php foreach($this->getUsers() as $user): ?>
    <tr>
      <td>
        <a href="/<?= $this->baseUri() . '/' . $user->id() . '/edit/'; ?>">
          <?= $user->username; ?>
        </a>
      </td>
      <td><?= $user->email; ?></td>
      <td><?= $user->displayName; ?></td>
      <td>
        <a href="/<?= $this->baseUri() . '/' . $user->id() . '/edit/'; ?>"
           title="Edit"><i class="icon-edit"></i></a>
        <a href="/<?= $this->baseUri() . '/' . $user->id() . '/delete/'; ?>"
           title="Delete"><i class="icon-trash"></i></a>
      </td>
    </tr>
  <?php endforeach; ?>
</table>

