<?php
/**
 * Author: oke.ugwu
 * Date: 31/07/13 10:15
 *
 * var $this \Qubes\Support\Applications\Back\Category\Views\Index
 */
?>
<h1>Platforms</h1>
<a href="/<?= $this->baseUri() . '/new'; ?>"
   class="btn btn-success pull-right"
   style="margin-top:-20px;">
  <i class="icon-plus icon-white"></i>
  Add Platform</a>
<div class="clearfix"></div>
<div style="margin-top:10px;"></div>
<?php if(Session::getFlash('msg')): ?>
  <div class="alert alert-<?= Session::getFlash('msg')->type; ?>">
    <?= Session::getFlash('msg')->text; ?>
  </div>
<?php endif; ?>
<table class="table table-striped table-bordered table-hover">
  <tr class="info">
    <th>Name</th>
    <th>Description</th>
    <th></th>
  </tr>
  <?php foreach($this->getPlatforms() as $platform): ?>
    <tr>
      <td>
        <a href="/<?= $this->baseUri() . '/' . $platform->id() . '/edit/'; ?>">
          <?= $platform->name; ?>
        </a>
      </td>
      <td><?= $platform->description; ?></td>
      <td>
        <a href="/<?= $this->baseUri() . '/' . $platform->id() . '/edit/'; ?>"
           title="Edit"><i class="icon-edit"></i></a>
        <a href="/<?= $this->baseUri() . '/' . $platform->id() . '/delete/'; ?>"
           title="Delete"><i class="icon-trash"></i></a>
      </td>
    </tr>
  <?php endforeach; ?>
</table>

