<?php
/**
 * Author: oke.ugwu
 * Date: 31/07/13 10:15
 *
 * @var $this \Qubes\Support\Applications\Back\Video\Views\Index
 */
?>
<h1>Videos</h1>
<a href="/<?= $this->baseUri() . '/new'; ?>"
   class="btn btn-success pull-right"
   style="margin-top:-20px;">
  <i class="icon-plus icon-white"></i>
  Add Video</a>
<div class="clearfix"></div>
<div style="margin-top:10px;"></div>
<?php if(Session::getFlash('msg')): ?>
  <div class="alert alert-<?= Session::getFlash('msg')->type; ?>">
    <?= Session::getFlash('msg')->text; ?>
  </div>
<?php endif; ?>
<table class="table table-striped table-bordered table-hover">
  <tr class="info">
    <th>#</th>
    <th>Title</th>
    <th>SubTitle</th>
    <th>URL</th>
    <th>Slug</th>
    <th></th>
  </tr>
  <?php foreach($this->getVideos() as $video): ?>
    <tr>
      <td><?= $video->order; ?></td>
      <td>
      <a href="/<?= $this->baseUri() . '/' . $video->id() . '/edit/'; ?>">
          <?= $video->title; ?>
        </a>
      </td>
      <td><?= $video->subTitle; ?></td>
      <td><?= $video->url; ?></td>
      <td><?= $video->slug; ?></td>
      <td>
        <a href="/<?= $this->baseUri() . '/' . $video->id() . '/edit/'; ?>"
           title="Edit"><i class="icon-edit"></i></a>
        <a href="/<?= $this->baseUri() . '/' . $video->id() . '/delete/'; ?>"
           title="Delete"><i class="icon-trash"></i></a>
      </td>
    </tr>
  <?php endforeach; ?>
</table>

