<?php
/**
 * Author: oke.ugwu
 * Date: 31/07/13 10:25
 *
 * @var $this \Qubes\Support\Applications\Back\Video\Views\VideoForm
 */
?>
<h1><?= $this->heading ?></h1>
<?= $this->form() ?>
<?php if($this->getVideo()->exists()): ?>
  <a class="btn btn-success"
     href="/<?= $this->baseUri() ?>/<?= $this->getVideo()->id(
     ) ?>/caption/<?= $this->getVideo()->id() ?>/edit">Edit Video Captions</a>
<?php endif; ?>
