<?php
/**
 * Author: oke.ugwu
 * Date: 31/07/13 13:26
 *
 * @var $this \Qubes\Support\Applications\Back\Article\Views\ArticleForm
 */
?>
<h1><?= $this->heading ?></h1>
<?= $this->form()->open() ?>
<?= $this->form()->getElement('id') ?>
<div class="row-fluid">
  <div class="span9">
    <?= $this->form()->getElement('title') ?>
    <?= $this->form()->getElement('subTitle') ?>
    <?= $this->form()->getElement('slug') ?>
    <?= $this->form()->getElement('view') ?>

    <?php foreach($this->getArticleSections() as $section): ?>
      <div style="margin-top:20px;" class="well">
        <ul class="nav nav-tabs platformBlocks">
          <?php foreach($this->getPlatforms() as $platform): ?>
            <li>
              <a href="#<?= $platform->name . $section->id() ?>"
                 class="<?= $platform->name ?>">
                <?= $platform->name ?>
              </a>
            </li>
          <?php endforeach; ?>
        </ul>


        <div class="tab-content" id="blockgroup<?= $section->id() ?>">
          <?php foreach($section->getBlocks() as $platformBlock): ?>
            <?php $formKey = "[" . $section->id(
              ) . "][" . $platformBlock->platformId . "]" ?>

            <div
              class="tab-pane"
              id="<?= $platformBlock->getPlatform()->name . $section->id() ?>">
              <div>
                <?= $this->form()->getElement('title' . $formKey) ?>
              </div>
              <?= $this->form()->getElement('content' . $formKey) ?>

              <?= $this->form()->getElement('submit' . $formKey) ?>

              <?php $deleteMsg = "Are you sure you want " .
                "to delete this section. You will lose all content for every " .
                "platform in this section"; ?>
              <a
                href="/<?= $this->baseUri() ?>/<?=
                $this->getArticle()->id() ?>/section/<?=
                $section->id() ?>/delete"
                class="btn btn-danger warn" alt="<?= $deleteMsg ?>">Delete
                                                                    Section</a>

              <a
                href="#" class="btn clear-block"
                id="clear-block<?= $formKey ?>">Clear Block</a>


              <div class="btn-group pull-right">
                <a href="#" class="btn">#<?= $section->order ?></a>
                <a
                  href="/<?= $this->baseUri() ?>/<?=
                  $this->getArticle()->id() ?>/section/<?=
                  $section->id() ?>/order/up"
                  class="btn"><i class="icon-arrow-up"></i></a>

                <a
                  href="/<?= $this->baseUri() ?>/<?=
                  $this->getArticle()->id() ?>/section/<?=
                  $section->id() ?>/order/down"
                  class="btn"><i class="icon-arrow-down"></i></a>
              </div>
            </div>

          <?php endforeach; ?>
          <div class="saved-success-wrapper hide">
            <div class="overlay"></div>
            <div class="text-success saved-success">SAVED :)</div>
          </div>
        </div>
        <!-- tab-content -->


      </div>
    <?php endforeach; ?>

  </div>


  <div class="span3">
    Category
    <?= $this->form()->getElement('categoryId'); ?>
    <?php if($this->getArticle()->exists()): ?>
      <a href="/admin/articles/preview/" class="btn">Preview Article</a>
      <br/><br/>
      <a
        href="/<?= $this->baseUri() ?>/<?=
        (int)$this->getArticle()->id() ?>/section/new"
        class="btn btn-success" id="add-section">Add Section</a>
      <br/><br/>
    <?php endif; ?>
    <?= $this->form()->getElement('submit') ?>
  </div>

</div>

<?= $this->form()->close() ?>
