<?php
/**
 * Author: oke.ugwu
 * Date: 31/07/13 13:18
 *
 * var $this \Qubes\Support\Applications\Back\Article\Views\Index
 */
?>
<h1>Articles</h1>
<a href="/<?= $this->baseUri() . '/new'; ?>"
   class="btn btn-success pull-right"
   style="margin-top:-20px;">
  <i class="icon-plus icon-white"></i>
  Add Article</a>
<div class="clearfix"></div>
<div style="margin-top:10px;"></div>
<?php if(Session::getFlash('msg')): ?>
  <div class="alert alert-<?= Session::getFlash('msg')->type; ?>">
    <?= Session::getFlash('msg')->message; ?>
  </div>
<?php endif; ?>
<table class="table table-striped table-bordered table-hover">
  <tr class="info">
    <th>Title</th>
    <th>Category</th>
    <th>Created</th>
    <th>Last Updated</th>
    <th></th>
  </tr>
  <?php foreach($this->getArticles() as $article): ?>
    <tr>
      <td>
        <a href="/<?= $this->baseUri() . '/' . $article->id() . '/edit/'; ?>">
          <?= $article->title; ?>
        </a>
      </td>
      <td><?= $article->categoryId; ?></td>
      <td><?= $article->createdAt; ?></td>
      <td><?= $article->updatedAt; ?></td>
      <td>
        <a href="/<?= $this->baseUri() . '/' . $article->id() . '/edit/'; ?>"
           title="Edit"><i class="icon-edit"></i></a>
        <a href="/<?= $this->baseUri() . '/' . $article->id() . '/delete/'; ?>"
           title="Delete"><i class="icon-trash"></i></a>
      </td>
    </tr>
  <?php endforeach; ?>
</table>

